In [99]:
import pandas as pd
from sklearn import model_selection

from Preprocessing import Preprocessing

data = pd.read_csv("disaster_prediction.csv", encoding="utf-8")

data.drop("choose_one_gold", axis=1, inplace=True) # removing columns we don't need
data.drop(data[data.choose_one == "Can't Decide"].index, inplace=True) # delete rows we don't need
# data.drop(data[data.confidence != 1].index, inplace=True) # delete rows with confidence != 1
data.drop(data[data.choose_one == "confidence"].index, inplace=True) # delete columns we don't need
data.drop_duplicates(subset="text", keep=False, inplace=True) # dropping duplicate values 


data.reset_index(inplace=True, drop=True) # reset the indices

# label the remaining data
data.choose_one[data.choose_one == "Not Relevant"] = 0
data.choose_one[data.choose_one == "Relevant"] = 1

# split the data into training and test
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data["text"], data["choose_one"], test_size=0.2)

# reset the indices for the Series and convert them to dataframes
Train_X.reset_index(inplace=True, drop=True)
Train_Y.reset_index(inplace=True, drop=True)

training_data = pd.concat([Train_X, Train_Y], axis=1) # getting the training data

Test_X.reset_index(inplace=True, drop=True)
Test_Y.reset_index(inplace=True, drop=True)

testing_data = pd.concat([Test_X, Test_Y], axis=1) # getting the testing data

# Preprocessing the training data
# preprocessed_train = Preprocessing(training_data)
training_data.to_csv("../Data/unconfident_training_data.csv") # saves the file in the ../Data directory

# # Preprocessing the testing data
# # preprocessed_test = Preprocessing(testing_data)
# testing_data.to_csv_file("unprocessed_testing_data") # saves the file in the ../Data directory

# train = pd.read_csv("../Data/preprocessed_training_data.csv", encoding="utf-8")
# test = pd.read_csv("../Data/preprocessed_testing_data.csv", encoding="utf-8")

/Users/haarithvohra/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/haarithvohra/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [89]:
data_unconfident = pd.read_csv("../Data/data_unconfident.csv")
# data_unconfident.drop(data_unconfident[data_unconfident.choose_one == "Can't Decide"].index, inplace=True)
data_unconfident = data_unconfident["choose_one"]

In [90]:
data_unconfident = data_unconfident.apply(lambda x: 1 if x == "Relevant" else 0)

In [91]:
unconfident_pred = pd.read_csv("../Data/unconfident_predictions.csv")

In [92]:
# unconfident_pred = unconfident_pred.to_numpy().flatten()

In [93]:
# data_unconfident = data_unconfident.to_numpy()

In [94]:
unconfident_df = pd.DataFrame()

In [95]:
unconfident_df["data_unconfident"] = data_unconfident
unconfident_df["unconfident_pred"] = unconfident_pred

In [49]:
unconfident_df.head()

   data_unconfident  unconfident_pred
0                 1                 0
1                 1                 0
2                 1                 0
3                 1                 1
4                 1                 0

In [51]:
results = unconfident_df["data_unconfident"] == unconfident_df["unconfident_pred"]

In [52]:
results.sum()

4044

In [53]:
unconfident_df.shape

(5830, 2)

In [ ]:
# unconfident predictions ==> data_unconfident

In [54]:
data_unconfident.head()

0    1
1    1
2    1
3    1
4    1
Name: choose_one, dtype: int64

In [55]:
data_uconf_df = pd.read_csv("../Data/data_unconfident.csv")
data_uconf_df

,choose_one,confidence,choose_one_gold,text
0,Relevant,0.9603,Relevant,"there is a forest fire at spot pond, geese are..."
1,Relevant,0.9606,Relevant\nCan't Decide,Apocalypse lighting. #Spokane #wildfires
2,Relevant,0.9607,Relevant\nCan't Decide,I'm on top of the hill and I can see a fire in...
3,Relevant,0.9215,Relevant,There's an emergency evacuation happening now ...
4,Relevant,0.7177,Relevant\nCan't Decide,I'm afraid that the tornado is coming to our a...
5,Relevant,0.9603,Relevant,Three people died from the heat wave so far
6,Relevant,0.6761,Relevant\nCan't Decide,#Flood in Bago Myanmar #We arrived Bago
7,Not Relevant,0.9612,Not Relevant,They'd probably still show more life than Arse...
8,Not Relevant,0.5945,Not Relevant\nCan't Decide,The end!
9,Relevant,0.8013,NaN,@bbcmtd Wholesale Markets ablaze http://t.co/l...
10,Relevant,0.6013,NaN,#AFRICANBAZE: Breaking news:Nigeria flag set a...
11,Not Relevant,0.6013,NaN,On plus side LOOK AT THE SKY LAST NIGHT IT WAS...
12,Not Relevant,0.7960,NaN,@PhDSquares #mufc they've built so much hype a...
13,Not Relevant,0.7959,NaN,Check these out: http://t.co/rOI2NSmEJJ http:/...
14,Not Relevant,0.5945,NaN,on the outside you're ablaze and alive\nbut yo...
15,Not Relevant,0.7959,NaN,Had an awesome time visiting the CFC head offi...
16,Not Relevant,0.7959,NaN,Building the perfect tracklist to life leave t...
17,Not Relevant,0.6000,NaN,beware world ablaze sierra leone &amp; guap.
18,Not Relevant,0.8317,NaN,Burning Man Ablaze! by Turban Diva http://t.co...
19,Relevant,0.6003,NaN,Man wife get six years jail for setting ablaze...
20,Relevant,0.7987,NaN,Rape victim dies as she sets herself ablaze: A...
21,Not Relevant,0.5031,NaN,SANTA CRUZ ��� Head of the St Elizabeth Police...
22,Not Relevant,0.5966,NaN,Noches El-Bestia '@Alexis_Sanchez: happy to se...
23,Relevant,0.7993,NaN,#Kurds trampling on Turkmen flag later set it ...
24,Not Relevant,0.8008,NaN,They sky was ablaze tonight in Los Angeles. I'...
25,Not Relevant,0.5994,NaN,@CTVToronto the bins in front of the field by ...
26,Not Relevant,0.8007,NaN,'Burning Rahm': Let's hope City Hall builds a ...
27,Not Relevant,0.5991,NaN,@ablaze what time does your talk go until? I d...
28,Not Relevant,0.8333,NaN,'I can't have kids cuz I got in a bicycle acci...
29,Not Relevant,0.5994,NaN,#stlouis #caraccidentlawyer Speeding Among Top...
...,...,...,...,...
5800,Not Relevant,0.7981,NaN,@widda16 ... He's gone. You can relax. I thoug...
5801,Not Relevant,0.5946,NaN,@jt_ruff23 @cameronhacker and I wrecked you both
5802,Not Relevant,0.6005,NaN,Three days off from work and they've pretty mu...
5803,Not Relevant,0.7976,NaN,@engineshed Great atmosphere at the British Li...
5804,Not Relevant,0.6054,NaN,Cramer: Iger's 3 words that wrecked Disney's s...
5805,Relevant,0.9601,Relevant,Pic of 16yr old PKK suicide bomber who detonat...
5806,Not Relevant,0.9198,Not Relevant,These boxes are ready to explode! Exploding Ki...
5807,Relevant,0.9602,Relevant,Calgary Police Flood Road Closures in Calgary....
5808,Relevant,0.6435,Relevant,#Sismo DETECTADO #Jap�_n 15:41:07 Seismic inte...
5809,Not Relevant,0.6324,Relevant,Sirens everywhere!
5810,Relevant,0.9604,Relevant,Omg earthquake
5811,Relevant,0.9601,Relevant,Officials: Alabama home quarantined over possi...
5812,Relevant,0.9210,Relevant,Heat wave warning aa? Ayyo dei. Just when I pl...
5813,Not Relevant,0.5696,Relevant,I just heard a really loud bang and everyone i...
5814,Relevant,0.9595,Relevant,RT @LivingSafely: #NWS issues Severe #Thunders...
5815,Relevant,0.9204,Relevant,Father-of-three Lost Control of Car After Over...
5816,Relevant,0.9608,Relevant,1.3 #Earthquake in 9Km Ssw Of Anza California ...
5817,Relevant,0.8809,Relevant,Evacuation order lifted for town of Roosevelt:...
5818,Relevant,0.8022,Relevant,To conference attendees! The blue line from th...
5819,Relevant,0.8018,Relevant,a siren just went off and it wasn't the Forney...
5820,Not Relevant,0.6678,Relevant,EARTHQUAKE SAFETY LOS ANGELES ��� SAFETY FASTE...
5821,Relevant,0.9601,Relevant,Officials say a quarantine is in place at an A...
5822,Relevant,0.9601,Relevant,#WorldNews Fallen powerlines on G:link tram: U...
5823,Relevant,0.8807,Relevant,on the flip side I'm at Walmart and there is a...
5824,Relevant,0.9601,Relevant,#stormchase Violent Record Breaking EF-5 El Re...
5825,Relevant,0.9201,Relevant,Green Line derailment in Chicago http://t.co/U...
5826,Relevant,0.7629,Relevant,M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...
5827,Relevant,0.9203,Relevant,Police investigating after an e-bike collided ...
5828,Relevant,0.8419,Relevant,MEG issues Hazardous Weather Outlook (HWO) htt...
5829,Relevant,0.8812,Relevant,#CityofCalgary has activated its Municipal Eme...

In [58]:
# replacing old (unconfident) labels with new predictions
data_uconf_df["choose_one"] = unconfident_pred

In [63]:
data_uconf_df.drop("confidence", axis=1, inplace=True)

In [64]:
data_uconf_df.head()

   choose_one                                               text
0           0  there is a forest fire at spot pond, geese are...
1           0           Apocalypse lighting. #Spokane #wildfires
2           0  I'm on top of the hill and I can see a fire in...
3           1  There's an emergency evacuation happening now ...
4           0  I'm afraid that the tornado is coming to our a...

In [78]:
training_data = pd.read_csv("../Data/training_data.csv").iloc[:, [2, 1]]

In [79]:
training_data.head()

   choose_one                                               text
0           1  We all complain about PA but atleast we don't ...
1           1  Still can't get over the thunderstorm/tornado ...
2           1  The Latest: More Homes Razed by Northern Calif...
3           0  @JoseBasedGod I'm obliterate you to the shadow...
4           0  @BenAffleck  i respected you and liked you for...

In [80]:
training_data_predicted = training_data.append(data_uconf_df, ignore_index=True)

In [82]:
training_data_predicted.tail()

      choose_one                                               text
9861           1  Green Line derailment in Chicago http://t.co/U...
9862           1  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...
9863           1  Police investigating after an e-bike collided ...
9864           1  MEG issues Hazardous Weather Outlook (HWO) htt...
9865           1  #CityofCalgary has activated its Municipal Eme...

In [83]:
4036 + 5830

9866

In [86]:
training_data_predicted.to_csv("../Data/training_data_predicted.csv", index=False)

In [88]:
pd.read_csv("../Data/training_data_predicted.csv").head()

   choose_one                                               text
0           1  We all complain about PA but atleast we don't ...
1           1  Still can't get over the thunderstorm/tornado ...
2           1  The Latest: More Homes Razed by Northern Calif...
3           0  @JoseBasedGod I'm obliterate you to the shadow...
4           0  @BenAffleck  i respected you and liked you for...

In [96]:
data_uconf_df.to_csv("../Data/soft_labels.csv", index=False)